/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SpendTrackersIndexImport } from './routes/spend-trackers/index'
import { Route as AddSpendTrackerIndexImport } from './routes/add-spend-tracker/index'
import { Route as AccountsIndexImport } from './routes/accounts/index'
import { Route as SpendTrackersSpendTrackerIdIndexImport } from './routes/spend-trackers/$spendTrackerId/index'
import { Route as AccountsAccountIdIndexImport } from './routes/accounts/$accountId/index'
import { Route as SpendTrackersSpendTrackerIdEditIndexImport } from './routes/spend-trackers/$spendTrackerId/edit/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SpendTrackersIndexRoute = SpendTrackersIndexImport.update({
  id: '/spend-trackers/',
  path: '/spend-trackers/',
  getParentRoute: () => rootRoute,
} as any)

const AddSpendTrackerIndexRoute = AddSpendTrackerIndexImport.update({
  id: '/add-spend-tracker/',
  path: '/add-spend-tracker/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsIndexRoute = AccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
} as any)

const SpendTrackersSpendTrackerIdIndexRoute =
  SpendTrackersSpendTrackerIdIndexImport.update({
    id: '/spend-trackers/$spendTrackerId/',
    path: '/spend-trackers/$spendTrackerId/',
    getParentRoute: () => rootRoute,
  } as any)

const AccountsAccountIdIndexRoute = AccountsAccountIdIndexImport.update({
  id: '/accounts/$accountId/',
  path: '/accounts/$accountId/',
  getParentRoute: () => rootRoute,
} as any)

const SpendTrackersSpendTrackerIdEditIndexRoute =
  SpendTrackersSpendTrackerIdEditIndexImport.update({
    id: '/spend-trackers/$spendTrackerId/edit/',
    path: '/spend-trackers/$spendTrackerId/edit/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexImport
      parentRoute: typeof rootRoute
    }
    '/add-spend-tracker/': {
      id: '/add-spend-tracker/'
      path: '/add-spend-tracker'
      fullPath: '/add-spend-tracker'
      preLoaderRoute: typeof AddSpendTrackerIndexImport
      parentRoute: typeof rootRoute
    }
    '/spend-trackers/': {
      id: '/spend-trackers/'
      path: '/spend-trackers'
      fullPath: '/spend-trackers'
      preLoaderRoute: typeof SpendTrackersIndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/spend-trackers/$spendTrackerId/': {
      id: '/spend-trackers/$spendTrackerId/'
      path: '/spend-trackers/$spendTrackerId'
      fullPath: '/spend-trackers/$spendTrackerId'
      preLoaderRoute: typeof SpendTrackersSpendTrackerIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/spend-trackers/$spendTrackerId/edit/': {
      id: '/spend-trackers/$spendTrackerId/edit/'
      path: '/spend-trackers/$spendTrackerId/edit'
      fullPath: '/spend-trackers/$spendTrackerId/edit'
      preLoaderRoute: typeof SpendTrackersSpendTrackerIdEditIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsIndexRoute
  '/add-spend-tracker': typeof AddSpendTrackerIndexRoute
  '/spend-trackers': typeof SpendTrackersIndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
  '/spend-trackers/$spendTrackerId': typeof SpendTrackersSpendTrackerIdIndexRoute
  '/spend-trackers/$spendTrackerId/edit': typeof SpendTrackersSpendTrackerIdEditIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsIndexRoute
  '/add-spend-tracker': typeof AddSpendTrackerIndexRoute
  '/spend-trackers': typeof SpendTrackersIndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
  '/spend-trackers/$spendTrackerId': typeof SpendTrackersSpendTrackerIdIndexRoute
  '/spend-trackers/$spendTrackerId/edit': typeof SpendTrackersSpendTrackerIdEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accounts/': typeof AccountsIndexRoute
  '/add-spend-tracker/': typeof AddSpendTrackerIndexRoute
  '/spend-trackers/': typeof SpendTrackersIndexRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/spend-trackers/$spendTrackerId/': typeof SpendTrackersSpendTrackerIdIndexRoute
  '/spend-trackers/$spendTrackerId/edit/': typeof SpendTrackersSpendTrackerIdEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/add-spend-tracker'
    | '/spend-trackers'
    | '/accounts/$accountId'
    | '/spend-trackers/$spendTrackerId'
    | '/spend-trackers/$spendTrackerId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/add-spend-tracker'
    | '/spend-trackers'
    | '/accounts/$accountId'
    | '/spend-trackers/$spendTrackerId'
    | '/spend-trackers/$spendTrackerId/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts/'
    | '/add-spend-tracker/'
    | '/spend-trackers/'
    | '/accounts/$accountId/'
    | '/spend-trackers/$spendTrackerId/'
    | '/spend-trackers/$spendTrackerId/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AddSpendTrackerIndexRoute: typeof AddSpendTrackerIndexRoute
  SpendTrackersIndexRoute: typeof SpendTrackersIndexRoute
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
  SpendTrackersSpendTrackerIdIndexRoute: typeof SpendTrackersSpendTrackerIdIndexRoute
  SpendTrackersSpendTrackerIdEditIndexRoute: typeof SpendTrackersSpendTrackerIdEditIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AddSpendTrackerIndexRoute: AddSpendTrackerIndexRoute,
  SpendTrackersIndexRoute: SpendTrackersIndexRoute,
  AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
  SpendTrackersSpendTrackerIdIndexRoute: SpendTrackersSpendTrackerIdIndexRoute,
  SpendTrackersSpendTrackerIdEditIndexRoute:
    SpendTrackersSpendTrackerIdEditIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accounts/",
        "/add-spend-tracker/",
        "/spend-trackers/",
        "/accounts/$accountId/",
        "/spend-trackers/$spendTrackerId/",
        "/spend-trackers/$spendTrackerId/edit/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accounts/": {
      "filePath": "accounts/index.tsx"
    },
    "/add-spend-tracker/": {
      "filePath": "add-spend-tracker/index.tsx"
    },
    "/spend-trackers/": {
      "filePath": "spend-trackers/index.tsx"
    },
    "/accounts/$accountId/": {
      "filePath": "accounts/$accountId/index.tsx"
    },
    "/spend-trackers/$spendTrackerId/": {
      "filePath": "spend-trackers/$spendTrackerId/index.tsx"
    },
    "/spend-trackers/$spendTrackerId/edit/": {
      "filePath": "spend-trackers/$spendTrackerId/edit/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
